services:
  taboo:
    image: ${REGISTRY}/${IMAGE_NAME}:${GITHUB_SHA}
    hostname: '{{.Node.Hostname}}'

    # Set the discord client secret and id as environment variables for the service
    environment:
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}

    # Connect the service to the "proxy" network for routing by Traefik
    networks:
      - proxy 

    # Store data in a named volume to persist data across container restarts
    volumes:
      - tabo-data:/data

    deploy:
      labels:
        # Enable Traefik to route traffic to this service
        - "traefik.enable=true"

        # Traefik forwards traffic to port 8080 of the taboo container
        - "traefik.http.services.taboo.loadbalancer.server.port=8080"

        # Route requests with host header "taboo.tabdiscord.com" to this service and enable TLS
        - "traefik.http.routers.taboo.rule=Host(`taboo.tabdiscord.com`)"
        - "traefik.http.routers.taboo.entrypoints=websecure"
        - "traefik.http.routers.taboo.tls.certresolver=cloudflare"

volumes:
  tabo-data: