basePath: /api
definitions:
  web.GameIDResponse:
    properties:
      createdAt:
        example: "2025-01-01T12:00:00Z"
        type: string
      gameId:
        example: 100
        type: integer
      picks:
        example:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        items:
          type: integer
        type: array
    type: object
host: taboo.tabdiscord.com
info:
  contact:
    name: Lachlan Cox
    url: https://github.com/aussiebroadwan/taboo/issues
  description: This API provides endpoints to fetch game results from the Taboo game
    backend, including the latest game, specific games by ID, and a range of games.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Taboo Game API
  version: "1.0"
paths:
  /api/game/{gameid}:
    get:
      description: Retrieves the results of a specific game given its ID, including
        its creation time and picks.
      parameters:
      - description: Game ID
        in: path
        name: gameid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Game result by ID
          schema:
            $ref: '#/definitions/web.GameIDResponse'
        "404":
          description: Unable to find game
          schema:
            type: string
        "500":
          description: Unexpected error responding
          schema:
            type: string
      summary: Get specific game results
      tags:
      - game
  /api/game/latest:
    get:
      description: Retrieves the most recent game ID, its creation time, and the list
        of picks.
      produces:
      - application/json
      responses:
        "200":
          description: Latest game result
          schema:
            $ref: '#/definitions/web.GameIDResponse'
        "404":
          description: Unable to find game
          schema:
            type: string
        "500":
          description: Unexpected error responding
          schema:
            type: string
      summary: Get latest game results
      tags:
      - game
  /api/game/range:
    get:
      description: Retrieves a list of game results starting from a given game ID.
      parameters:
      - description: Starting game ID
        in: query
        name: start
        required: true
        type: integer
      - description: Number of games to return (max 100)
        in: query
        name: count
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of game results
          schema:
            items:
              $ref: '#/definitions/web.GameIDResponse'
            type: array
        "400":
          description: Invalid query parameters
          schema:
            type: string
        "500":
          description: Unexpected error responding
          schema:
            type: string
      summary: Get a range of game results
      tags:
      - game
schemes:
- https
swagger: "2.0"
